
import { Gift } from './types';

export const giftDefinitions: Gift[] = [
    // Regular Gifts
    {
        id: 'heart',
        name: 'Heart',
        price: 10,
        currency: 'gold',
        icon: 'heart',
        category: 'regular',
    },
    {
        id: 'star-regular',
        name: 'Star',
        price: 25,
        currency: 'gold',
        icon: 'star',
        category: 'regular',
    },
    {
        id: 'smile-regular',
        name: 'Smile',
        price: 50,
        currency: 'gold',
        icon: 'smile',
        category: 'regular',
    },

    // VIP Gifts
    { id: 'clown', name: 'Clown', price: 100, currency: 'gold', icon: '/gifts/clown.svg', category: 'vip' },
    { id: 'coffee', name: 'Coffee', price: 110, currency: 'gold', icon: '/gifts/coffee.svg', category: 'vip' },
    { id: 'cool', name: 'Cool', price: 120, currency: 'gold', icon: '/gifts/cool.svg', category: 'vip' },
    { id: 'like', name: 'Like', price: 130, currency: 'gold', icon: '/gifts/like.svg', category: 'vip' },
    { id: 'smile', name: 'Smile', price: 140, currency: 'gold', icon: '/gifts/smile.svg', category: 'vip' },
    { id: 'cure', name: 'Cure', price: 150, currency: 'gold', icon: '/gifts/cure.svg', category: 'vip' },
    { id: 'energy', name: 'Energy', price: 160, currency: 'gold', icon: '/gifts/energy.svg', category: 'vip' },
    { id: 'fishbone', name: 'Fishbone', price: 170, currency: 'gold', icon: '/gifts/fishbone.svg', category: 'vip' },
    { id: 'poison', name: 'Poison', price: 180, currency: 'gold', icon: '/gifts/poison.svg', category: 'vip' },
    { id: 'star', name: 'Star', price: 190, currency: 'gold', icon: '/gifts/star.svg', category: 'vip' },
    { id: 'flowers', name: 'Flowers', price: 200, currency: 'gold', icon: '/gifts/flowers.svg', category: 'vip' },
    { id: 'gift', name: 'Gift Box', price: 210, currency: 'gold', icon: '/gifts/gift.svg', category: 'vip' },
    { id: 'hot', name: 'Hot', price: 220, currency: 'gold', icon: '/gifts/hot.svg', category: 'vip' },
    { id: 'icecream', name: 'Ice Cream', price: 230, currency: 'gold', icon: '/gifts/icecream.svg', category: 'vip' },
    { id: 'karma', name: 'Karma', price: 240, currency: 'gold', icon: '/gifts/karma.svg', category: 'vip' },
    { id: 'kiss', name: 'Kiss', price: 250, currency: 'gold', icon: '/gifts/kiss.svg', category: 'vip' },
    { id: 'love', name: 'Love', price: 260, currency: 'gold', icon: '/gifts/love.svg', category: 'vip' },
    { id: 'rose', name: 'Rose', price: 270, currency: 'gold', icon: '/gifts/rose.svg', category: 'vip' },
    { id: 'voodoo', name: 'Voodoo Doll', price: 280, currency: 'gold', icon: '/gifts/voodoo.svg', category: 'vip' },
    { id: 'lovepotion', name: 'Love Potion', price: 300, currency: 'gold', icon: '/gifts/lovepotion.svg', category: 'vip' },
    { id: 'loverepair', name: 'Heart Repair', price: 310, currency: 'gold', icon: '/gifts/loverepair.svg', category: 'vip' },
    { id: 'medal', name: 'Medal', price: 320, currency: 'gold', icon: '/gifts/medal.svg', category: 'vip' },
    { id: 'pizza', name: 'Pizza', price: 330, currency: 'gold', icon: '/gifts/pizza.svg', category: 'vip' },
    { id: 'power', name: 'Power', price: 350, currency: 'gold', icon: '/gifts/power.svg', category: 'vip' },
    { id: 'ring', name: 'Ring', price: 400, currency: 'gold', icon: '/gifts/ring.svg', category: 'vip' },
    { id: 'teddy', name: 'Teddy Bear', price: 450, currency: 'gold', icon: '/gifts/teddy.svg', category: 'vip' },
    { id: 'crown', name: 'Crown', price: 500, currency: 'gold', icon: '/gifts/crown.svg', category: 'vip' },
    { id: 'trophy', name: 'Trophy', price: 600, currency: 'gold', icon: '/gifts/trophy.svg', category: 'vip' },
    { id: 'diamond', name: 'Diamond', price: 750, currency: 'gold', icon: '/gifts/diamond.svg', category: 'vip' },
    { id: 'money', name: 'Money', price: 800, currency: 'gold', icon: '/gifts/money.svg', category: 'vip' },
    { id: 'goldpot', name: 'Pot of Gold', price: 1000, currency: 'gold', icon: '/gifts/goldpot.svg', category: 'vip' },

    // Premium Gifts
    {
        id: 'ruby-gem',
        name: 'Ruby',
        price: 100,
        currency: 'rubies',
        icon: '/interface_icons/ruby.svg',
        category: 'premium',
    },
    {
        id: 'king-crown',
        name: 'King',
        price: 250,
        currency: 'rubies',
        icon: '/gifts/king.gif',
        category: 'premium',
    },
    {
        id: 'queen-crown',
        name: 'Queen',
        price: 250,
        currency: 'rubies',
        icon: '/gifts/queen.gif',
        category: 'premium',
    },
    {
        id: 'superstar',
        name: 'Superstar',
        price: 500,
        currency: 'rubies',
        icon: '/gifts/superstar.gif',
        category: 'premium',
    },
    {
        id: 'diamond-gem',
        name: 'Diamond',
        price: 1000,
        currency: 'rubies',
        icon: '/gifts/Diamond.gif',
        category: 'premium',
    }
];
